### ISSUE TITLE
Typing placeholder text starting with "p" causes a put

### ISSUE THREAD

**Issue by jmcantrell** [Jorenar/miniSnip#44]
Given a snippet with a placeholder like:
```
<{foo}>
```

It's easier to see if you yank some text into the default register first. Then after inserting it, and when the cursor is on the placeholder text "foo", typing "p" will insert the previously yanked text.

**Comment by Jorenar** [comment]
Hmm, I am unable to reproduce. Could you please prepare a minimalistic config where such bug occurs?

**Comment by jmcantrell** [comment]
Apologies. This is due to the [vim-wayland-clipboard](https://github.com/jasonccox/vim-wayland-clipboard) plugin.

I would appreciate any insight you might have as to why this normal mode mapping might conflict with your plugin.

https://github.com/jasonccox/vim-wayland-clipboard/blob/master/plugin/wayland_clipboard.vim#L95

**Comment by jmcantrell** [comment]
TIL that vmaps apply for select mode. I think I need to suggest that the other plugin use xmap instead.

**Comment by Jorenar** [comment]
Ah, glad you got it figured out then!

<sub>By the way, if you are interested, I also have [fauxClip](https://github.com/Jorenar/fauxClip) plugin, which adds various clipboard supports</sub>

**Comment by jmcantrell** [comment]
Thanks, I will check that out.
